name: Catherine Lee
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
description: > # this means to ignore newlines until "baseurl:"
  Exploring coding, writing, and life
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "catherinelee274.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  catherinelee274
